version: '3.4'

networks:
  elastic-stack-example:

services:

  elasticsearch-security-setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch-security-setup
    networks:
      elastic-stack-example:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    networks:
      elastic-stack-example:
    depends_on:
      elasticsearch-security-setup:
        condition: service_healthy

  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    container_name: logstash
    networks:
      elastic-stack-example:
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana    
    networks:
      elastic-stack-example:
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana-init:
    image: alpine:latest
    container_name: kibana-init
    networks:
      elastic-stack-example:
    depends_on:
      kibana:
        condition: service_healthy

  fleet-server:
      depends_on:
        kibana:
          condition: service_healthy
        elasticsearch:
          condition: service_healthy
      image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
      container_name: fleet-server
      networks:
        elastic-stack-example:

  elasticstack-api:
    image: ${DOCKER_REGISTRY-}elasticstack-api
    container_name: elasticstack-api
    build:
      context: .
      dockerfile: Services/ElasticStack/ElasticStack.API/Dockerfile
    networks:
      elastic-stack-example:
    depends_on:
      - logstash
