version: '3.4'

services:

  elasticsearch:
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200"
      - "9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - type: bind
        source: Logging/elasticsearch/elasticsearch.yml
        target: /etc/elasticsearch/elasticsearch.yml
        read_only: true
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  logstash:
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    expose:
      - "5000"
      - "5044"
      - "9600"
    volumes:
      - type: bind
        source: Logging/logstash/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        read_only: true
      - type: bind
        source: Logging/logstash/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true

  kibana:
    volumes:
      - kibana-data:/usr/share/kibana/data
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    expose:
      - "5601"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail -X GET localhost:5601/api/index_management/indices -H 'kbn-xsrf:true' || exit 1"]
      interval: 1s
      timeout: 3s
      retries: 30

  elasticstack-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"

  kibana-init:
    volumes:
      - type: bind
        source: Logging/kibana/dashboards.ndjson
        target: /usr/share/kibana/data/dashboards.ndjson
        read_only: true
    working_dir: /usr/share/kibana/data
    command:
      - /bin/sh
      - -c
      - |
        apk --no-cache add curl
        curl -i -X POST http://kibana:5601/api/saved_objects/_import -H 'kbn-xsrf:true' --form file=@dashboards.ndjson

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
